services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=keycloak-test-users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
